chat/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = "Chat"

urlpatterns = [
    path('', views.index, name='index'),
    path('user', views.UserLoginRegister, name='user'),
    path('logout/',views.logoutUser,name='logout'),
    path('info/<str:user_name>/',views.account_view,name='viewinfo'),
    path('info/<str:user_name>/edit/',views.edit_account_view,name='edit_account'),
    path('chatroom/<int:room_id>', views.room,name='room'),
    path('myrooms/', views.myrooms, name='myrooms'),
    path('delete_room/<int:room_id>', views.deleteRoom, name='deleteroom'),
    path('escape_room/<int:room_id>', views.escapeRoom, name='escaperoom'),
    path('update_room/<int:room_id>', views.updateRoom, name='updateroom')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chatty/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('chat.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
 

chat/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.fields import NullBooleanField

class Information(models.Model):
    imagelink = models.ImageField(upload_to='users/',null=True,blank = True)
    birthday = models.DateTimeField()
    # status = models.BooleanField(default=False)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    def __str__(self):
        return self.user.username

class Room(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=300)
    password = models.CharField(max_length=100)
    def __str__(self):
        return self.name

class RoomHistory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    status = models.BooleanField(default=False)
    def __str__(self):
        return f"{self.user.username} go to {self.room}"

# Create your models here.
class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    content = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    class Meta:
        ordering = ('date_added',)
    def __str__(self):
        return f"Message from User {self.user.username} in room {self.room.name}"

chat/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Room

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

chat/views.py
from django.http.response import HttpResponse
from django.shortcuts import redirect, render
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.contrib import messages
from .forms import CreateUserForm
from .models import Message, Room, RoomHistory,Information
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User

import datetime


@login_required(login_url='Chat:user')
def index(request):
    # rooms = Room.objects.all()
    rhs = RoomHistory.objects.filter(user=request.user)
    rooms = [rh.room for rh in rhs]
    rhs = RoomHistory.objects.all()
    if request.method == 'POST':
        if 'create-room' in request.POST:
            room_name = request.POST.get('room-name')
            password = request.POST.get('room-pwd')
            room = Room.objects.filter(user=request.user, name=room_name).first()
            if room == None:
                room = Room.objects.create(user=request.user, name=room_name, password=password)
                RoomHistory.objects.create(user=request.user, room=room)
            return redirect("Chat:room", room_id=room.id)
        elif 'search-room' in request.POST:
            room_name = request.POST.get('room-name')
            if room_name != "":
                rooms = Room.objects.all()
                rooms = [room for room in rooms if room.name.lower().find(room_name.lower())!=-1]
    # create info user
    if Information.objects.filter(user=request.user).exists() ==False:
        d= datetime.date(2000,1,1)
        Information.objects.create(user=request.user,imagelink='/person.png',birthday=d)
    info_entity = Information.objects.filter(user=request.user).first()
    return render(request, 'chat/index.html', {"rhs": rhs, "rooms": rooms, "user_name": request.user.username,"info_entity":info_entity})


@login_required(login_url='Chat:user')
def room(request, room_id):
    room_entity = Room.objects.filter(id=room_id).first()
    if room_entity == None:
        messages.info(request, 'Khong co phong nay!')
        return redirect("Chat:index")
    if not RoomHistory.objects.filter(room=room_entity, user=request.user).exists():
        room_password=""
        if request.method == "POST":
            room_password = request.POST.get('room-pwd')
        room_entity = Room.objects.filter(id=room_id, password=room_password).first()
        if room_entity == None:
            messages.info(request, 'Mat khau sai!')
            return redirect("Chat:index")
        RoomHistory.objects.create(user=request.user, room=room_entity)
    username = request.user.username
    mgs = Message.objects.filter(room=room_entity)
    mgs = mgs[int(len(mgs)/15):]
    info_entity = Information.objects.filter(user=request.user).first()
    rhs = RoomHistory.objects.filter(room=room_entity)
    infors = [Information.objects.filter(user=rh.user).first() for rh in rhs]
    return render(request, 'chat/room.html', {'room_entity': room_entity, 'username': username, 'messagesUser': mgs, "info_entity":info_entity,"infors":infors})

@login_required(login_url='Chat:user')
def myrooms(request):
    rooms = Room.objects.filter(user = request.user)
    if 'create-room' in request.POST:
        room_name = request.POST.get('room-name')
        password = request.POST.get('room-pwd')
        room = Room.objects.filter(user=request.user, name=room_name).first()
        if room == None:
            room = Room.objects.create(user=request.user, name=room_name, password=password)
            RoomHistory.objects.create(user=request.user, room=room)
        return redirect("Chat:room", room_id=room.id)
    elif 'search-room' in request.POST:
        room_name = request.POST.get('room-name')
        if room_name != "":
            rooms = [room for room in rooms if room.name.lower().find(room_name.lower())!=-1]
    # create info user
    if Information.objects.filter(user=request.user).exists() == False:
        d= datetime.date(2000,1,1)
        Information.objects.create(user=request.user,imagelink='/person.png',birthday=d)
    info_entity = Information.objects.filter(user=request.user).first()
    return render(request, 'chat/myrooms.html', {"rooms": rooms, "user_name": request.user.username,"info_entity":info_entity})

def UserLoginRegister(request):
    if request.user.is_authenticated:
        return redirect('Chat:index')
    else:
        if request.method != 'POST':
            form = CreateUserForm()
        else:
            if 'Sign-up' in request.POST:
                form = CreateUserForm(data=request.POST)
                if form.is_valid():
                    form.save()
                    userSignUp = form.cleaned_data.get('username')
                    messages.success(
                        request, 'Account was created for ' + userSignUp)

            elif 'Login' in request.POST:
                username = request.POST.get('user_signin')
                password = request.POST.get('pwd_signin')
                user = authenticate(
                    request, username=username, password=password)

                if user is not None:
                    login(request, user)
                    return redirect('Chat:index')
                else:
                    messages.info(
                        request, 'Username or password is incorrect!')
                    return redirect('Chat:user')
        context = {'form': form}
        return render(request, 'User/User.html', context)

@login_required(login_url='Chat:user')
def deleteRoom(request,room_id):
    room = Room.objects.get(id=room_id)
    if room.user == request.user:
        room.delete()
        messages.info(request,'delete successfully!')
    else:
        messages.info(request,'Invalid user!')
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

@login_required(login_url='Chat:user')
def escapeRoom(request,room_id):
    room = Room.objects.get(id=room_id)
    rh = RoomHistory.objects.get(room=room,user=request.user)
    if rh != None:
        rh.delete()
        messages.info(request,'escape successfully!')
    else:
        messages.info(request,'Invalid processing!')
    return redirect('Chat:index')

@login_required(login_url='Chat:user')
def updateRoom(request, room_id):
    room = Room.objects.get(id=room_id)
    info_entity = Information.objects.filter(user=request.user).first()

    if (request.method == "POST"):
        roomName = request.POST.get('room-name-update')
        roomPwd = request.POST.get('room-pwd-update')
        if (room.password == roomPwd):
            if not 'chk-update-room-pwd' in request.POST:
                room.name = roomName
                Room.save(room)
                messages.info(request, 'Update Room Name successfully')
                return redirect("Chat:index")
            else:
                newPwd = request.POST.get('room-new-pwd-update')
                confirmPwd = request.POST.get('room-confirm-pwd-update')
                if newPwd == confirmPwd:
                    room.name = roomName
                    room.password = newPwd
                    Room.save(room)
                    messages.info(request, 'Update Password successfully')
                    return redirect("Chat:index")
                else:
                    messages.info(request, 'New password and confirm password didn\'t match!')
        else:
            messages.info(request, 'Password is incorrect!')

    context = {'room': room, 'username': request.user.username, "info_entity":info_entity}
    return render(request, 'chat/update.html', context)

def logoutUser(request):
    logout(request)
    return redirect('Chat:user')

def account_view(request,user_name):
    # getID_room = 
    if Information.objects.filter(user=request.user).exists() ==False:
        d= datetime.date(2000,1,1)
        Information.objects.create(user=request.user,imagelink='/person.png',birthday=d)
    info_entity = Information.objects.filter(user=request.user).first()  
    return render(request,'user/info.html',{'info_entity':info_entity,'username':request.user.username})

@login_required(login_url='Chat:user')
def edit_account_view(request,user_name):
    info_entity = Information.objects.filter(user=request.user).first()
    if request.method == 'POST':
        user_name_edit = request.POST.get('username')
        birth_day = request.POST.get('birthday')
        image_link = request.FILES.get('profileimage')
        
        User.objects.filter(username=request.user).update(username=user_name_edit)
        
        info_entity.birthday= birth_day
        if image_link != None:
            info_entity.imagelink=image_link
        info_entity.save()
        
        return redirect('Chat:viewinfo',user_name_edit)
        
    return render(request,"user/edit_info.html",{"info_entity":info_entity})

chat/templates/chat/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/index-style.css' %}">
    <link rel="stylesheet" href="{% static 'css/reponsive.css' %}">
    <link rel="stylesheet" href="{% static 'css/loading.css' %} ">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.13.0/themes/base/jquery-ui.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/ui/1.13.0/jquery-ui.js"></script>
    <title>Chat Application</title>
</head>

<body>
    <div class="load-page">
        <div class="loadingBx">
            <div class="loading"></div>
        </div>
    </div>    
    <div class="input-room">
        <form id="form-room-input" method="post" action="">
            {% csrf_token %}
            <div class="btn-close-form">
                <ion-icon name="close-circle"></ion-icon>
            </div>
            <div>Room Name</div>
            <input type="text" name="room-name" id="room-name" autocomplete="off" required maxlength="30">
            <div>Password</div>
            <input type="password" name="room-pwd" id="room-pwd">
            <input type="submit" name="create-room" value="Create New Room">
        </form>
    </div>

    {% block navTop%}
    {% endblock %}
    <header id="header">
        <div class="btn-home"><a href="{% url 'Chat:index' %}"><ion-icon name="home"></ion-icon></a></div>
        <h1>Chat application</h1>
        <div id="info">
            <div id="user">
                <div id="img-user">
                    <img src="{{info_entity.imagelink.url}}" alt="img-user">
                </div>
                <div id="user-name">Welcome,<span>{{info_entity.user}}</span></div>
            </div>
            <div id="setting">
                <ion-icon class="btn-setting" name="settings"></ion-icon>
            </div>
            <ul class="setting-menu">
                <li><div id="btn-view-mode" onclick="changeMode()"><ion-icon name="sunny"></ion-icon>Light Mode</div></li>
                <li><a href="{% url 'Chat:viewinfo' request.user.username %}">Profile</a></li>
                <li><a href="{% url 'Chat:myrooms' %}">My Rooms</a></li>
                <li><a href="{% url 'Chat:logout' %}">Logout</a></li>
            </ul>
        </div>
    </header>

    <div id="message-dialog-feature" style="display: none;">
        <p id="message-feature"></p>
    </div>

    {% block content %}
    {% endblock %}
    <footer>
        <p>Copyright &copy by <a href="#">MRL</a>, All Rights Reserved</p>
    </footer>

    {%if messages%}
        {%for message in messages %}                                    
            <script>
                $(document).ready(function() {
                    $('#message-feature').html("{{message}}")
                    $('#message-dialog-feature').dialog({
                    autoOpen: true,
                    show: {effect: "blind", duration: 500},
                    hide: {effect: "explode", duration: 500},
                    height: "auto", 
                    resizable: false,
                    title: "Messages"  
                    })
                })
            </script>
        {%endfor%}    
    {%endif%} 
</body>

<script src="https://unpkg.com/ionicons@4.5.10-0/dist/ionicons.js"></script>
<script  src="{% static 'js/script.js' %}"></script>
<script src="{% static 'js/main-script.js' %}"></script>
{% block script %}
{% endblock %}
</html>

chat/templates/chat/index.html
{% extends "chat/base.html" %}

{% block navTop%}
    <a class="btn-header" href="#header">
        <ion-icon name="arrow-round-up"></ion-icon>
    </a>
{% endblock %}

{% block content %}
    {% load poll_extras %}    
    <section class="content">

        <div class="in-add-room">
            <div class="btn-add-room">+</div>
            <form method="post"  action="">
                {% csrf_token %}
                <input type="search" name="room-name" id="search-room-name" autocomplete="off" placeholder="Search Room Name">
                <input type="submit" name="search-room" id="search-room" value="Search">
            </form>            
        </div>

        <div class="list-room">
             {%for room in rooms%}
            <div class="room">
                <div class="title-room">
                    <h2 class="title">{{room.name}}</h2>
                    {% csrf_token %}
                    {%if room.password == "" or rhs|user_filter:room|user_compare:request.user%}
                        <a href="{% url 'Chat:room' room.id %}" class="btn-join">Join Now</a>
                    {%else%}
                        <div class="btn-join btn-input-pwd-room">Join Now <span><ion-icon name="lock"></ion-icon></div>
                        <div class="input-room-pwd">
                            <form method="post" action="{% url 'Chat:room' room.id %}">
                                {% csrf_token %}
                                <input type="password" name="room-pwd" id="room-pwd" placeholder="Input Password Here" required>
                                <input type="submit" value="Join">                           
                            </form>         
                            <div class="btn-close-room-pwd"><ion-icon name="close"></ion-icon></div>                
                        </div>                       
                    {%endif%}
                </div>
                <div class="room-info">
                    <p class="date-create">Created By {{room.user.username}}</p>

                    {% if rhs|user_filter:room|user_compare:request.user %}
                    <div class="room-menu">
                        {% if room.user.username == user_name %}
                            <a href="{% url 'Chat:updateroom' room.id %}">Update</a>
                            <a class="btnDelete" onclick='showDeleteRoomDialog("{{room.name}}", "{{room.id}}")'>Delete</a>                              
                        {%else%}
                            <a class="btnDelete" onclick='showEscapeRoomDialog("{{room.name}}", "{{room.id}}")'>Escape</a> 
                        {% endif %}           
                    </div>
                    {% endif %} 
                </div>
            </div>
            {%endfor%}
        </div>
    </section>
{% endblock %}

{% block script %}
<script>
    let btnAddRoom = document.querySelector('.btn-add-room');
    let divInputRoom = document.querySelector('.input-room');
    let btnCloseForm = document.querySelector('.btn-close-form');
    
    let btnInputPwdRoom = document.querySelectorAll('.btn-input-pwd-room');
    let divInputRoomPwd = document.querySelectorAll('.input-room-pwd');
    let btnCloseRoomPwd = document.querySelectorAll('.btn-close-room-pwd');

    for (var i = 0; i < btnInputPwdRoom.length; i++) {
        btnInputPwdRoom[i].addEventListener('click', function(i) {
            btnInputPwdRoom[i].parentElement.classList.add('hidden');
            btnInputPwdRoom[i].classList.add('hidden');
            divInputRoomPwd[i].classList.add('show');
        }.bind(this, i));
    }

    for (var i = 0; i < btnCloseRoomPwd.length; i++) {
        btnCloseRoomPwd[i].addEventListener('click', function(i) {
            btnInputPwdRoom[i].parentElement.classList.remove('hidden');
            btnInputPwdRoom[i].classList.remove('hidden');
            divInputRoomPwd[i].classList.remove('show');
        }.bind(this, i));
    }

    btnAddRoom.onclick = function() {
        divInputRoom.classList.add('show');
    }

    btnCloseForm.onclick = function() {
        divInputRoom.classList.remove('show');
    }     
    
    function showDeleteRoomDialog(room_name, room_id) {
        $('#message-feature').html("Do you want to delete <span class=\"span-dialog\">&quot;" + room_name + "&quot;</span>");
        $('#message-dialog-feature').dialog({
            autoOpen: true,
            show: {effect: "blind", duration: 200},
            hide: {effect: "explode", duration: 200},
            height: "auto", 
            resizable: false,
            title: "Messages",
            modal: true,
            buttons: {
                "Yes": function() {
                    window.location.replace("delete_room/" + room_id);
                },
                "No": function() {
                    $(this).dialog("close");
                }
            }
        });
    }

    function showEscapeRoomDialog(room_name, room_id) {
        $('#message-feature').html("Do you want to escape <span class=\"span-dialog\">&quot;" + room_name + "&quot;</span>");
        $('#message-dialog-feature').dialog({
            autoOpen: true,
            show: {effect: "blind", duration: 200},
            hide: {effect: "explode", duration: 200},
            height: "auto", 
            resizable: false,
            title: "Messages",
            modal: true,
            buttons: {
                "Yes": function() {
                    window.location.replace("escape_room/" + room_id);
                },
                "No": function() {
                    $(this).dialog("close");
                }
            }
        });
    }
</script>
{% endblock %}

chat/templates/chat/myrooms.html
{% extends "chat/base.html" %}

{% block navTop%}
    <a class="btn-header" href="#header">
        <ion-icon name="arrow-round-up"></ion-icon>
    </a>
{% endblock %}

{% block content %}
    {% load poll_extras %}

    <div id="message-dialog-delete" style="display: none;">
        <p id="message-delete"></p>
    </div>
    
    <section class="content">

        <div class="in-add-room">
            <div class="btn-add-room">+</div>
            <form method="post"  action="">
                {% csrf_token %}
                <input type="search" name="room-name" id="search-room-name" autocomplete="off" placeholder="Search Room Name">
                <input type="submit" name="search-room" id="search-room" value="Search">
            </form>            
        </div>

        <div class="list-room">
            {%for room in rooms%}
            <div class="room">
                <div class="title-room">
                    <h2 class="title">{{room.name}}</h2>
                    <a href="{% url 'Chat:room' room.id %}" class="btn-join">Join Now</a>                    
                </div>
                <div class="room-info">
                    <p class="date-create">Created By {{room.user.username}}</p>
                    <div class="room-menu">
                        <a href="{% url 'Chat:updateroom' room.id %}">Update</a>
                        <a class="btnDelete" onclick='showDeleteRoomDialog("{{room.name}}", "{{room.id}}")'>Delete</a>
                    </div>
                </div>
            </div>
            {%endfor%}
        </div>
    </section>

    {%if messages%}
        {%for message in messages %}                                    
            <script>
                $(document).ready(function() {
                    $('#message-delete').html("{{message}}")
                    $('#message-dialog-delete').dialog({
                    autoOpen: true,
                    show: {effect: "blind", duration: 500},
                    hide: {effect: "explode", duration: 500},
                    height: "auto", 
                    resizable: false,
                    title: "Messages"  
                    })
                })
            </script>
        {%endfor%}    
    {%endif%} 
{% endblock %}

{% block script %}
<script>
    let btnAddRoom = document.querySelector('.btn-add-room');
    let divInputRoom = document.querySelector('.input-room');
    let btnCloseForm = document.querySelector('.btn-close-form');
    
    let btnInputPwdRoom = document.querySelectorAll('.btn-input-pwd-room');
    let divInputRoomPwd = document.querySelectorAll('.input-room-pwd');
    let btnCloseRoomPwd = document.querySelectorAll('.btn-close-room-pwd');

    for (var i = 0; i < btnInputPwdRoom.length; i++) {
        btnInputPwdRoom[i].addEventListener('click', function(i) {
            btnInputPwdRoom[i].parentElement.classList.add('hidden');
            btnInputPwdRoom[i].classList.add('hidden');
            divInputRoomPwd[i].classList.add('show');
        }.bind(this, i));
    }

    for (var i = 0; i < btnCloseRoomPwd.length; i++) {
        btnCloseRoomPwd[i].addEventListener('click', function(i) {
            btnInputPwdRoom[i].parentElement.classList.remove('hidden');
            btnInputPwdRoom[i].classList.remove('hidden');
            divInputRoomPwd[i].classList.remove('show');
        }.bind(this, i));
    }

    btnAddRoom.onclick = function() {
        divInputRoom.classList.add('show');
    }

    btnCloseForm.onclick = function() {
        divInputRoom.classList.remove('show');
    }     
    
    function showDeleteRoomDialog(room_name, room_id) {
        $('#message-delete').html("Do you want to delete <span class=\"span-dialog\">&quot;" + room_name + "&quot;</span>");
        $('#message-dialog-delete').dialog({
            autoOpen: true,
            show: {effect: "blind", duration: 200},
            hide: {effect: "explode", duration: 200},
            height: "auto", 
            resizable: false,
            title: "Messages",
            modal: true,
            buttons: {
                "Yes": function() {
                    window.location.replace("/delete_room/" + room_id);
                },
                "No": function() {
                    $(this).dialog("close");
                }
            }
        });
    }
</script>
{% endblock %}

chat/templates/chat/room.html
{% extends "chat/base.html" %}

{% block content %}
    <section class="room-content">
        <div class="left-bx">
            <div class="title-message-bx">
                <h2>Room Name: <span>{{room_entity.name}}</span></h2>
                <div class="btn-group-people" onclick="showListUser()"><ion-icon name="people"></ion-icon></div>
            </div>            
            <div id="message-list">
                {% for m in messagesUser%}
                <div class="message-display">
                    <h3>{{ m.user.username }}<span class="date-create">{{m.date_added|date:'d/m/Y H:i'}}</span></h3>
                    <p class="message-content">
                        {{ m.content }}
                    </p>
                </div>                  
                {% endfor %}             
            </div>
            <form id="message-form-input" onsubmit="return false">
                <input type="text" data-emoji="true" name="message-input" id="message-input" placeholder="Type your messages" autocomplete="off" maxlength="1000" autofocus>
                <input type="submit" value="Send" id="btn-send">
            </form>
        </div>   
        <div class="right-bx">
            <h2>List User In Room</h2>
            <div class="list-user">
                 {% for info in infors %}
                    <!-- <div class="user-box">
                        <div class="avatar"><img src="{{info.imagelink.url}}" alt="avatar-user"></div>
                        <div class="username" id="{{info.user.id}}">{{info.user}} 
                        <small id="status"></small></div> 
                    </div> -->
                    <div class="user-box" id="{{info.user.id}}">
                        <div class="avatar">
                            <div class="avatar-img"><img src="{{info.imagelink.url}}" alt="avatar-user"></div>
                            <div class="status"></div>
                        </div>
                        <div class="username">{{info.user}}</div>
                    </div>     
                {% endfor %}
            </div>
        </div>                                           
    </section>
{% endblock %}

{% block script %}
    {{ room_entity.id|json_script:"json-room_id" }}
    {{ username|json_script:"json-username" }}
    <script>        
        const roomID = JSON.parse(document.getElementById('json-room_id').textContent);
        const userName = JSON.parse(document.getElementById('json-username').textContent);

        (() => {
            window.EmojiPicker.init()
        })()    
      
        function scrollToBottom() {
            let objDiv = document.getElementById("message-list");
            objDiv.scrollTop = objDiv.scrollHeight;
        }

        function showListUser() {
            let RoomContent = document.querySelector('.room-content');
            RoomContent.classList.toggle('show');
        }

        scrollToBottom();

        
        const chatSocket = new WebSocket(
            'ws://'
            + window.location.host
            + '/ws/'
            + roomID
            + '/'
        );

        const in_room = () => {
            setTimeout(() => {
                chatSocket.send(JSON.stringify({
                    'status': 'WENT_ONLINE',
                    'username':userName,
                    'room_id': roomID,
                    'type_set':"USERS"
                }))
            }, 1000)
        }

        chatSocket.onmessage = function (e) {
            console.log('onmessage');
            
            const data = JSON.parse(e.data);
            if(data.type_set==="CHAT")
            {
                if (data.message) {
                    var html = '<div class="message-display"><h3> ' + data.username + '<span class="date-create">' + data.date + '</span></h3><p class="message-content">' + data.message + '</p></div>'  
                    document.querySelector('#message-list').innerHTML += html;
                } else {
                    alert('The message is empty!');
                }
                scrollToBottom();
           }else if(data.type_set==="USERS"){
                //alert(data.status === "ONLINE")
                if(data.status == "ONLINE"){
                    document.getElementById(data.user_id).classList.add('online')
                    //alert(data.user_id)
                }else if(data.status == "OFFLINE"){
                    document.getElementById(data.user_id).classList.remove('online')
                }
            }
        };

        chatSocket.onclose = function (e) {
            console.log('The socket close unexpectadly');
        };

        document.querySelector('#btn-send').onclick = function (e) {
            const messageInputDom = document.querySelector('#message-input');
            const message = messageInputDom.value;

            if (message === "") {
                return;
            }            
            chatSocket.send(JSON.stringify({
                'message': message,
                'username': userName,
                'room_id': roomID,
                'type_set':"CHAT"
            }));            
            
            // alert(message);
            messageInputDom.value = "";
        };

        chatSocket.onopen = in_room()
    </script>
{% endblock %}