chat/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = "Chat"

urlpatterns = [
    path('', views.index, name='index'),
    path('user', views.UserLoginRegister, name='user'),
    path('logout/',views.logoutUser,name='logout'),
    path('info/<str:user_name>/',views.account_view,name='viewinfo'),
    path('info/<str:user_name>/edit/',views.edit_account_view,name='edit_account'),
    path('chatroom/<int:room_id>', views.room,name='room'),
    path('myrooms/', views.myrooms, name='myrooms'),
    path('delete_room/<int:room_id>', views.deleteRoom, name='deleteroom'),
    path('escape_room/<int:room_id>', views.escapeRoom, name='escaperoom'),
    path('update_room/<int:room_id>', views.updateRoom, name='updateroom')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chatty/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('chat.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
 

chat/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.fields import NullBooleanField

class Information(models.Model):
    imagelink = models.ImageField(upload_to='users/',null=True,blank = True)
    birthday = models.DateTimeField()
    # status = models.BooleanField(default=False)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    def __str__(self):
        return self.user.username

class Room(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=300)
    password = models.CharField(max_length=100)
    def __str__(self):
        return self.name

class RoomHistory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    status = models.BooleanField(default=False)
    def __str__(self):
        return f"{self.user.username} go to {self.room}"

# Create your models here.
class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    content = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    class Meta:
        ordering = ('date_added',)
    def __str__(self):
        return f"Message from User {self.user.username} in room {self.room.name}"

chat/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Room

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

chat/views.py
from django.http.response import HttpResponse
from django.shortcuts import redirect, render
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.contrib import messages
from .forms import CreateUserForm
from .models import Message, Room, RoomHistory,Information
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User

import datetime


@login_required(login_url='Chat:user')
def index(request):
    # rooms = Room.objects.all()
    rhs = RoomHistory.objects.filter(user=request.user)
    rooms = [rh.room for rh in rhs]
    rhs = RoomHistory.objects.all()
    if request.method == 'POST':
        if 'create-room' in request.POST:
            room_name = request.POST.get('room-name')
            password = request.POST.get('room-pwd')
            room = Room.objects.filter(user=request.user, name=room_name).first()
            if room == None:
                room = Room.objects.create(user=request.user, name=room_name, password=password)
                RoomHistory.objects.create(user=request.user, room=room)
            return redirect("Chat:room", room_id=room.id)
        elif 'search-room' in request.POST:
            room_name = request.POST.get('room-name')
            if room_name != "":
                rooms = Room.objects.all()
                rooms = [room for room in rooms if room.name.lower().find(room_name.lower())!=-1]
    # create info user
    if Information.objects.filter(user=request.user).exists() ==False:
        d= datetime.date(2000,1,1)
        Information.objects.create(user=request.user,imagelink='/person.png',birthday=d)
    info_entity = Information.objects.filter(user=request.user).first()
    return render(request, 'chat/index.html', {"rhs": rhs, "rooms": rooms, "user_name": request.user.username,"info_entity":info_entity})


@login_required(login_url='Chat:user')
def room(request, room_id):
    room_entity = Room.objects.filter(id=room_id).first()
    if room_entity == None:
        messages.info(request, 'Khong co phong nay!')
        return redirect("Chat:index")
    if not RoomHistory.objects.filter(room=room_entity, user=request.user).exists():
        room_password=""
        if request.method == "POST":
            room_password = request.POST.get('room-pwd')
        room_entity = Room.objects.filter(id=room_id, password=room_password).first()
        if room_entity == None:
            messages.info(request, 'Mat khau sai!')
            return redirect("Chat:index")
        RoomHistory.objects.create(user=request.user, room=room_entity)
    username = request.user.username
    mgs = Message.objects.filter(room=room_entity)
    mgs = mgs[int(len(mgs)/15):]
    info_entity = Information.objects.filter(user=request.user).first()
    rhs = RoomHistory.objects.filter(room=room_entity)
    infors = [Information.objects.filter(user=rh.user).first() for rh in rhs]
    return render(request, 'chat/room.html', {'room_entity': room_entity, 'username': username, 'messagesUser': mgs, "info_entity":info_entity,"infors":infors})

@login_required(login_url='Chat:user')
def myrooms(request):
    rooms = Room.objects.filter(user = request.user)
    if 'create-room' in request.POST:
        room_name = request.POST.get('room-name')
        password = request.POST.get('room-pwd')
        room = Room.objects.filter(user=request.user, name=room_name).first()
        if room == None:
            room = Room.objects.create(user=request.user, name=room_name, password=password)
            RoomHistory.objects.create(user=request.user, room=room)
        return redirect("Chat:room", room_id=room.id)
    elif 'search-room' in request.POST:
        room_name = request.POST.get('room-name')
        if room_name != "":
            rooms = [room for room in rooms if room.name.lower().find(room_name.lower())!=-1]
    # create info user
    if Information.objects.filter(user=request.user).exists() == False:
        d= datetime.date(2000,1,1)
        Information.objects.create(user=request.user,imagelink='/person.png',birthday=d)
    info_entity = Information.objects.filter(user=request.user).first()
    return render(request, 'chat/myrooms.html', {"rooms": rooms, "user_name": request.user.username,"info_entity":info_entity})

def UserLoginRegister(request):
    if request.user.is_authenticated:
        return redirect('Chat:index')
    else:
        if request.method != 'POST':
            form = CreateUserForm()
        else:
            if 'Sign-up' in request.POST:
                form = CreateUserForm(data=request.POST)
                if form.is_valid():
                    form.save()
                    userSignUp = form.cleaned_data.get('username')
                    messages.success(
                        request, 'Account was created for ' + userSignUp)

            elif 'Login' in request.POST:
                username = request.POST.get('user_signin')
                password = request.POST.get('pwd_signin')
                user = authenticate(
                    request, username=username, password=password)

                if user is not None:
                    login(request, user)
                    return redirect('Chat:index')
                else:
                    messages.info(
                        request, 'Username or password is incorrect!')
                    return redirect('Chat:user')
        context = {'form': form}
        return render(request, 'User/User.html', context)

@login_required(login_url='Chat:user')
def deleteRoom(request,room_id):
    room = Room.objects.get(id=room_id)
    if room.user == request.user:
        room.delete()
        messages.info(request,'delete successfully!')
    else:
        messages.info(request,'Invalid user!')
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

@login_required(login_url='Chat:user')
def escapeRoom(request,room_id):
    room = Room.objects.get(id=room_id)
    rh = RoomHistory.objects.get(room=room,user=request.user)
    if rh != None:
        rh.delete()
        messages.info(request,'escape successfully!')
    else:
        messages.info(request,'Invalid processing!')
    return redirect('Chat:index')

@login_required(login_url='Chat:user')
def updateRoom(request, room_id):
    room = Room.objects.get(id=room_id)
    info_entity = Information.objects.filter(user=request.user).first()

    if (request.method == "POST"):
        roomName = request.POST.get('room-name-update')
        roomPwd = request.POST.get('room-pwd-update')
        if (room.password == roomPwd):
            if not 'chk-update-room-pwd' in request.POST:
                room.name = roomName
                Room.save(room)
                messages.info(request, 'Update Room Name successfully')
                return redirect("Chat:index")
            else:
                newPwd = request.POST.get('room-new-pwd-update')
                confirmPwd = request.POST.get('room-confirm-pwd-update')
                if newPwd == confirmPwd:
                    room.name = roomName
                    room.password = newPwd
                    Room.save(room)
                    messages.info(request, 'Update Password successfully')
                    return redirect("Chat:index")
                else:
                    messages.info(request, 'New password and confirm password didn\'t match!')
        else:
            messages.info(request, 'Password is incorrect!')

    context = {'room': room, 'username': request.user.username, "info_entity":info_entity}
    return render(request, 'chat/update.html', context)

def logoutUser(request):
    logout(request)
    return redirect('Chat:user')

def account_view(request,user_name):
    # getID_room = 
    if Information.objects.filter(user=request.user).exists() ==False:
        d= datetime.date(2000,1,1)
        Information.objects.create(user=request.user,imagelink='/person.png',birthday=d)
    info_entity = Information.objects.filter(user=request.user).first()  
    return render(request,'user/info.html',{'info_entity':info_entity,'username':request.user.username})

@login_required(login_url='Chat:user')
def edit_account_view(request,user_name):
    info_entity = Information.objects.filter(user=request.user).first()
    if request.method == 'POST':
        user_name_edit = request.POST.get('username')
        birth_day = request.POST.get('birthday')
        image_link = request.FILES.get('profileimage')
        
        User.objects.filter(username=request.user).update(username=user_name_edit)
        
        info_entity.birthday= birth_day
        if image_link != None:
            info_entity.imagelink=image_link
        info_entity.save()
        
        return redirect('Chat:viewinfo',user_name_edit)
        
    return render(request,"user/edit_info.html",{"info_entity":info_entity})

chat/templates/user/User.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet"  href="{% static 'css/user-style.css' %}">
    <link rel="stylesheet"  href="{% static 'css/reponsive-user.css' %}">
    <link rel="stylesheet" href="{% static 'css/loading.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <title>Login</title>
</head>
<body>
    <div class="load-page">
        <div class="loadingBx">
            <div class="loading"></div>
        </div>
    </div>
    <div class="login">
        <!-- Form Đăng Nhập -->
        <form class="face sign-in" method="POST" action="">
            {% csrf_token %}
            <h2>Sign In</h2>
            <div class="box">
                <input type="text" placeholder="Username" name="user_signin" autocomplete="on" required>
            </div>
            <div class="box">
                <input type="password" class="password" placeholder="Password" name="pwd_signin" required>
                <div class="toggle" onclick="showPassword(0)"></div>
            </div>
            <input type="submit" name="Login" value="Login" class="btnLogin">
            <div class="query">
                <p>Forgot <a href="#">Password</a>?</p>
                <p>Create an <span id="sign-up">Account</span>?</p>
            </div>

            {%if messages%}
                {%for message in messages %}                                    
                    <p class="message">{{message}}</p>
                {%endfor%}    
            {%endif%}   
        </form>        

        <!-- Form Đăng Ký -->
        <form class="face sign-up" method="POST" action="">
            {% csrf_token %}
            <h2>Sign UP</h2>
            <div class="box">
                <!-- <input type="text" placeholder="Username" name="user_signup"> -->
                {{form.username}}
            </div>
            <div class="box">
                <!-- <input type="password" class="password" placeholder="Password" name="pwd_signup"> -->
                {{form.password1}}
                <div class="toggle" onclick="showPassword(1)"></div>
            </div>
            <div class="box">
                <!-- <input type="password" class="password" placeholder="Confirm Password" name="pwd_signup"> -->
                {{form.password2}}
                <div class="toggle" onclick="showPassword(2)"></div>
            </div>
            <input type="submit" name="Sign-up" value="Sign up" class="btnLogin">
            <div class="query">
                <p>Have an account, <span id="sign-in">Sign In</span>?</p>
            </div>
        </form>        
    </div>   
    <div class="error">
        {{form.errors}}
    </div>     
</body>
<script>
    $(window).on("load", function() {
        $(".load-page").fadeOut(1000);
    });
    let password = document.getElementsByClassName('password');
    let toggle = document.getElementsByClassName('toggle');
    let btnSignIn = document.getElementById('sign-in');
    let btnSignUp = document.getElementById('sign-up');
    let password1 = document.getElementById('id_password1');
    let password2 = document.getElementById('id_password2');
    let username = document.getElementById('id_username');

    const login = document.querySelector('.login');

    password1.className += 'password';
    password2.className += 'password';

    username.setAttribute('placeholder', 'Username');
    password1.setAttribute('placeholder', 'Password');
    password2.setAttribute('placeholder', 'Confirm Password');
    
    function showPassword(i) {
        if (password[i].type === 'password') {
            password[i].setAttribute('type', 'text');
            toggle[i].classList.add('hide');
        }
        else {
            password[i].setAttribute('type', 'password');
            toggle[i].classList.remove('hide');
        }
    }

    btnSignUp.onclick = function() {
        login.classList.add('sign-up');
    }

    btnSignIn.onclick = function() {
        login.classList.remove('sign-up');
    }
</script>
</html>

chat/templates/user/edit_info.html
{% extends "chat/base.html" %}

{% block content %}
    {% load poll_extras %}
    <div class="content-info edit">
        <h1>Edit Information</h1>
        <form class="info-bx"  method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="img-user">
                <label for="file-upload">
                    <ion-icon name="camera"></ion-icon>
                    <input type="file" name="profileimage" id="file-upload">
                </label>
                <img id="avatar-info" src="{{info_entity.imagelink.url}}">    
            </div> 
            <div class="config-info">
                <label for="datepicker">User Name: <input type="text" name="username" id="user-name-info" value={{info_entity.user}}></label>  
                <label for="datepicker">Day of birth: <input type="date" name="birthday" value="{{info_entity.birthday|date:'Y-m-d'}}"></label>  
                <div class="btn-info">
                    <button type="submit">Confirm</button>
                </div>          
            </div>              
        </form>         
    </div>
{% endblock %}

{% block script %}
<script>
    let btnFile = document.querySelector("#file-upload");
    let img = document.querySelector("#avatar-info");

    btnFile.addEventListener('change', function() {
        const file = this.files[0];
        if (file) {
            const reader = new FileReader();
            reader.onload = function() {
                const result = reader.result;
                img.src = result;
            }
            reader.readAsDataURL(file);
        }
    });
</script>
{% endblock %}

chat/templates/user/info.html
{% extends "chat/base.html" %}

{% block content %}
    {% load poll_extras %}
    <div class="content-info">
        <h1>Information</h1>
        <div class="info-bx">
            <div class="img-user">
                <img id="avatar-info" src="{{info_entity.imagelink.url}}">    
            </div> 
            <div class="config-info">
                <p class="p-info">User Name: <span>{{username}}</span></p>  
                <p class="p-info">Day Of Birth: <span>{{info_entity.birthday|date:'d/m/Y'}}</span></p>  
                <div class="btn-info">
                    <a href="{% url 'Chat:edit_account' request.user.username %}">Update</a>
                    <a href="">Change Password</a>
                    <a class="btn-delete-acc" href="">Delete Account</a>
                </div>          
            </div>              
        </div>         
    </div>
{% endblock %}